# Generated by Django 5.0.4 on 2024-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_note_unique_examen_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(default='mail@uha.fr', max_length=254),
        ),
    ]
