# Generated by Django 5.0.6 on 2024-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sae_alter_enseignant_email_saeue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='numero_professeur',
        ),
        migrations.AddField(
            model_name='ue',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examen',
            name='coefficient',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
