# Generated by Django 5.0.6 on 2024-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_enseignant_numero_professeur_ue_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
    ]
