# Generated by Django 5.0.4 on 2024-06-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ue_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='sae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sae'),
        ),
    ]
