# Generated by Django 5.0.4 on 2024-06-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_examen_sae'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='numero_professeur',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ressource'),
        ),
    ]
